name: midea-mqtt-bridge

services:
  midea-bridge:
    image: ghcr.io/sidey79/midea-mqtt:0.1.1@sha256:1950066c52822b7c9f31065e063af968cf59f75677ff18fe2c6881bc89dfe19c
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      MQTT_HOST: ${MQTT_HOST:-fhem}
      MQTT_PORT: ${MQTT_PORT:-1883}
      MQTT_USER: ${MQTT_USER:-}
      MQTT_PASSWORD: ${MQTT_PASSWORD:-}
      MIDEA_AC_HOST: ${MIDEA_AC_HOST}
      MIDEA_AC_PORT: ${MIDEA_AC_PORT:-6444}
      MIDEA_AC_ID: ${MIDEA_AC_ID:-}
      MIDEA_AC_TOKEN: ${MIDEA_AC_TOKEN:-}
      MIDEA_AC_KEY: ${MIDEA_AC_KEY:-}
      MIDEA_POLL_INTERVAL: ${MIDEA_POLL_INTERVAL:-30}
      MIDEA_TOPIC_BASE: ${MIDEA_TOPIC_BASE:-midea/klima}
    networks:
      - midea-internal
    restart: unless-stopped

networks:
  midea-internal:
    name: midea-mqtt-internal
    internal: true
